#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Amin Saberi

# make output directory
mkdir -p out_dir

# run the actual python code
# this docker image is simply ubuntu + nilearn and a few other python packages
singularity exec docker://faskowit/app-fmri-2-mat:brnch-0.1.2 python3 main.py
